# Generated by Django 5.1.7 on 2025-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msite", "0002_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comments/"),
        ),
    ]
