# Generated by Django 5.1.7 on 2025-12-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msite", "0003_comment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
    ]
